name: cbh
ref_x: t
min: 0
max: 1
res_min: -0.5
res_max: 0.5
uom: "[unitless]"
comps:
  - c1
  - c2
  - e5

bin_size: 0.01
c1:
  fn: ""
  column: 2
  data: ""
  data_res: ""
  var_name: ""
c2:
  fn: ""
  column: 2
  data: ""
  data_res: ""
  var_name: ""
e5:
  fn: ""
  column: ""
  data: ""
  data_res: ""
  var_name: ""
t:
  fn: ""
  column: ""
  data: ""
  data_res: ""
t1:
  fn: ""
  column: ""
  data: ""
  data_res: ""
t2:
  fn: ""
  column: ""
  data: ""
  data_res: ""
