name: cbh
ref_x: t
min: 0
max: 10000
res_min: -2000
res_max: 2000
uom: "[m]"
comps:
  - c1
  - c2
  - e5

bin_size: 100
c1:
  fn: "thaao_c1_cloud_base_"
  column: 2
  data: ""
  data_res: ""
  var_name: "cdcb"
c2:
  fn: "thaao_c2_cloud_base_"
  column: 2
  data: ""
  data_res: ""
  var_name: "cdcb"
e5:
  fn: "thaao_e5_cloud_base_height_"
  column: 2
  data: ""
  data_res: ""
  var_name: "cbh"
t:
  fn: "_Thule_CHM190147_000_0010_0060cloud"
  column: "CBH_L1[m]"
  data: ""
  data_res: ""
t1:
  fn: ""
  column: ""
  data: ""
  data_res: ""
t2:
  fn: ""
  column: ""
  data: ""
  data_res: ""
