name: dewpt
ref_x: ""
min: ""
max: ""
res_min: ""
res_max: ""
uom: "[deg]"
comps: []
bin_size: null
c1:
  fn: ""
  column: ""
  data: ""
  data_res: ""
  var_name: ""
c2:
  fn: ""
  column: ""
  data: ""
  data_res: ""
  var_name: ""
e:
  fn: "thaao_e_2m_dewpoint_temperature_"
  column: ""
  data: ""
  data_res: ""
  var_name: "d2m"
t:
  fn: ""
  column: ""
  data: ""
  data_res: ""
t1:
  fn: ""
  column: ""
  data: ""
  data_res: ""
t2:
  fn: ""
  column: ""
  data: ""
  data_res: ""
