name: iwv
ref_x: t
min: 0
max: 20
res_min: -5
res_max: 5
uom: "[mm]"
comps:
  - c1
  - c2
  - e5
  - t1

bin_size: 0.1

c1:
  fn: "thaao_c1_total_column_integrated_water_vapour_"
  column: 2
  data: ""
  data_res: ""
  var_name: "tciwv"

c2:
  fn: "thaao_c2_total_column_integrated_water_vapour_"
  column: 2
  data: ""
  data_res: ""
  var_name: "tciwv"
  
e5:
  fn: "thaao_e5_total_column_water_vapour_"
  column: 2
  data: ""
  data_res: ""
  var_name: "tcwv"

t:
  fn: ""
  column: ""
  data: ""
  data_res: ""

t1:
  fn: "IWV_15_min_all"
  column: "IWV[kg/m2]"
  data: ""
  data_res: ""
  