name: lw_down
ref_x: t
min: 100
max: 400
res_min: -20
res_max: 20
uom: "[W/m2]"
comps:
  - c1
  - c12
  - e
bin_size: 2
c1:
  fn: "thaao_c1_thermal_surface_radiation_downwards_"
  column: 4
  data: ""
  data_res: ""
  var_name: "strd"
c2:
  fn: "thaao_c2_thermal_surface_radiation_downwards_"
  column: 4
  data: ""
  data_res: ""
  var_name: "strd"
e:
  fn: "thaao_e_surface_thermal_radiation_downwards_"
  column: 2
  data: ""
  data_res: ""
  var_name: "strd"
t:
  fn: "MERGED_SW_LW_UP_DW_METEO_"
  column: "LW_DOWN"
  data: ""
  data_res: ""
t1:
  fn: ""
  column: ""
  data: ""
  data_res: ""
t2:
  fn: ""
  column: ""
  data: ""
  data_res: ""
