name: lw_net
ref_x: t
min: -150
max: 50
res_min: -20
res_max: 20
uom: "[W/m2]"
comps:
  - c1
  - c2
  - e5
bin_size: 2
c1:
  fn: "thaao_c1_surface_net_thermal_radiation_"
  column: 4
  data: ""
  data_res: ""
  var_name: "str"
c2:
  fn: "thaao_c2_surface_net_thermal_radiation_"
  column: 4
  data: ""
  data_res: ""
  var_name: "str"
e5:
  fn: "thaao_e5_surface_net_thermal_radiation_"
  column: 2
  data: ""
  data_res: ""
  var_name: "str"
t:
  fn: ""
  column: ""
  data: ""
  data_res: ""
t1:
  fn: ""
  column: ""
  data: ""
  data_res: ""
t2:
  fn: ""
  column: ""
  data: ""
  data_res: ""
