name: lw_up
ref_x: t
min: 150
max: 450
res_min: -20
res_max: 20
uom: "[W/m2]"
comps:
  - c1
  - c2
  - e
bin_size: 2
c1:
  fn: ""
  column: ""
  data: ""
  data_res: ""
  var_name: ""
c2:
  fn: ""
  column: ""
  data: ""
  data_res: ""
  var_name: ""
e:
  fn: ""
  column: ""
  data: ""
  data_res: ""
  var_name: ""
t:
  fn: "MERGED_SW_LW_UP_DW_METEO_"
  column: "LW_UP"
  data: ""
  data_res: ""
t1:
  fn: ""
  column: 2
  data: ""
  data_res: ""
t2:
  fn: ""
  column: 2
  data: ""
  data_res: ""
