name: lwp
ref_x: t1
min: 0
max: 50
res_min: -20
res_max: 20
uom: "[kg/m2]"
comps:
  - c1
  - c2
  - e
bin_size: 2
c1:
  fn: "thaao_c1_total_column_cloud_liquid_water_"
  column: 2
  data: ""
  data_res: ""
  var_name: "tclw"
c2:
  fn: "thaao_c2_total_column_cloud_liquid_water_"
  column: 2
  data: ""
  data_res: ""
  var_name: "tclw"
e:
  fn: "thaao_e_total_column_cloud_liquid_water_"
  column: 2
  data: ""
  data_res: ""
  var_name: "tclw"
t:
  fn: ""
  column: ""
  data: ""
  data_res: ""
t1:
  fn: "LWP_15_min_all"
  column: "LWP[g/m2]"
  data: ""
  data_res: ""
t2:
  fn: ""
  column: .nan
  data: ""
  data_res: ""
