name: orog
ref_x: c
min: 0
max: 25
res_min: -25
res_max: 25
uom: "[m]"
comps:
  - c
  - c2
  - e
bin_size: 0.05

c:
  fn: "thaao_c_orography_"
  column: ""
  data: ""
  data_res: ""
  var_name: "orog"

c2:
  fn: "thaao_c2_orography_"
  column: ""
  data: ""
  data_res: ""
  var_name: "orog"

e:
  fn: "thaao_e_geopotential_"
  column: ""
  data: ""
  data_res: ""
  var_name: "z"

t:
  fn: ""
  column: ""
  data: ""
  data_res: ""

t1:
  fn: ""
  column: ""
  data: ""
  data_res: ""
  