name: orog
ref_x: c
min: 0
max: 300
res_min: -500
res_max: 500
uom: "[m]"
comps: 
  - c
  - e
bin_size: 0.05

c:
  fn: "thaao_c_orography_"
  column: ""
  data: ""
  data_res: ""
  var_name: "orog"

e:
  fn: "thaao_e_geopotential_"
  column: ""
  data: ""
  data_res: ""
  var_name: "z"

t:
  fn: ""
  column: ""
  data: ""
  data_res: ""

t1:
  fn: ""
  column: ""
  data: ""
  data_res: ""
  