name: orog
ref_x: c
min: 0
max: 25
res_min: -25
res_max: 25
uom: "[m]"
comps:
  - c1
  - c2
  - e5
bin_size: 0.05

c1:
  fn: "thaao_c1_orography_"
  column: ""
  data: ""
  data_res: ""
  var_name: "orog"

c2:
  fn: "thaao_c2_orography_"
  column: ""
  data: ""
  data_res: ""
  var_name: "orog"

e5:
  fn: "thaao_e5_geopotential_"
  column: ""
  data: ""
  data_res: ""
  var_name: "z"

t:
  fn: ""
  column: ""
  data: ""
  data_res: ""

t1:
  fn: ""
  column: ""
  data: ""
  data_res: ""
  