name: rh
ref_x: t
min: 20
max: 100
res_min: -10
res_max: 10
uom: "[%]"
comps:
  - c
  - c2
  - e
  - t2
bin_size: 0.5
c:
  fn: "thaao_c_2m_relative_humidity_"
  column: ""
  data: ""
  data_res: ""
  var_name: "r2"
c2:
  fn: "thaao_c2_2m_relative_humidity_"
  column: ""
  data: ""
  data_res: ""
  var_name: "r2"
e:
  fn: ""
  column: ""
  data: ""
  data_res: ""
  var_name: ""
t:
  fn: "Meteo_weekly_all"
  column: "RH_%"
  data: ""
  data_res: ""
t1:
  fn: ""
  column: ""
  data: ""
  data_res: ""
t2:
  fn: "AWS_THAAO_"
  column: "RH"
  data: ""
  data_res: ""
