name: surf_pres
ref_x: t
min: 900
max: 1050
res_min: -10
res_max: 10
uom: "[hPa]"
comps:
  - c
  - c2
  - e
  - t2
bin_size: 0.5
c:
  fn: "thaao_c_surface_pressure_"
  column: 2
  data: ""
  data_res: ""
  var_name: "sp"
c2:
  fn: "thaao_c2_surface_pressure_"
  column: 2
  data: ""
  data_res: ""
  var_name: "sp"
e:
  fn: "thaao_e_surface_pressure_"
  column: 2
  data: ""
  data_res: ""
  var_name: "sp"
t:
  fn: "Meteo_weekly_all"
  column: "BP_hPa"
  data: ""
  data_res: ""
t1:
  fn: ""
  column: ""
  data: ""
  data_res: ""
t2:
  fn: "AWS_THAAO_"
  column: "BP_mbar"
  data: ""
  data_res: ""
