name: sw_down
ref_x: t
min: 0
max: 800
res_min: -20
res_max: 20
uom: "[W/m2]"
comps:
  - c1
  - c2
  - e
bin_size: 2
c1:
  fn: "thaao_c1_surface_solar_radiation_downwards_"
  column: 4
  data: ""
  data_res: ""
  var_name: "ssrd"
c2:
  fn: "thaao_c2_surface_solar_radiation_downwards_"
  column: 4
  data: ""
  data_res: ""
  var_name: "ssrd"
e:
  fn: "thaao_e_surface_solar_radiation_downwards_"
  column: 2
  data: ""
  data_res: ""
  var_name: "ssrd"
t:
  fn: "MERGED_SW_LW_UP_DW_METEO_"
  column: "SW_DOWN"
  data: ""
  data_res: ""
t1:
  fn: ""
  column: ""
  data: ""
  data_res: ""
t2:
  fn: ""
  column: ""
  data: ""
  data_res: ""
