name: sw_lw_net
ref_x: t
min: 0
max: 800
res_min: -20
res_max: 20
uom: "[W/m2]"
comps:
  - c1
  - c2
  - e5
bin_size: 2
c1:
  fn: ""
  column: 
  data: ""
  data_res: ""
  var_name: ""
c2:
  fn: ""
  column: 
  data: ""
  data_res: ""
  var_name: ""
e5:
  fn: ""
  column: ""
  data: ""
  data_res: ""
  var_name: ""
t:
  fn: ""
  column: ""
  data: ""
  data_res: ""
t1:
  fn: ""
  column: ""
  data: ""
  data_res: ""
t2:
  fn: ""
  column: ""
  data: ""
  data_res: ""
