name: sw_net
ref_x: t
min: 0
max: 600
res_min: -20
res_max: 20
uom: "[W/m2]"
comps:
  - c
  - c2
  - e
bin_size: 2
c:
  fn: "thaao_c_surface_net_solar_radiation_"
  column: 4
  data: ""
  data_res: ""
  var_name: "ssr"
c2:
  fn: "thaao_c2_surface_net_solar_radiation_"
  column: 4
  data: ""
  data_res: ""
  var_name: "ssr"
e:
  fn: "thaao_e_surface_net_solar_radiation_"
  column: 2
  data: ""
  data_res: ""
  var_name: "ssr"
t:
  fn: ""
  column: ""
  data: ""
  data_res: ""
t1:
  fn: ""
  column: ""
  data: ""
  data_res: ""
t2:
  fn: ""
  column: ""
  data: ""
  data_res: ""
