name: tcc
ref_x: t
min: 0
max: 9
res_min: -9
res_max: 9
uom: "[%]"
comps:
  - c1
  - c2
  - e
bin_size: 1
c1:
  fn: "thaao_c1_total_cloud_cover_"
  column: 2
  data: ""
  data_res: ""
  var_name: "tcc"
c2:
  fn: "thaao_c2_total_cloud_cover_"
  column: 2
  data: ""
  data_res: ""
  var_name: "tcc"
e:
  fn: "thaao_e_total_cloud_cover_"
  column: 2
  data: ""
  data_res: ""
  var_name: "tcc"
t:
  fn: "_Thule_CHM190147_000_0060cloud"
  column: "TCC[okt]"
  data: ""
  data_res: ""
  var_name: "tcc"
t1:
  fn: ""
  column: ""
  data: ""
  data_res: ""
  var_name: ""
t2:
  fn: ""
  column: ""
  data: ""
  data_res: ""
  var_name: ""
