name: windv
ref_x: t2
min: -25
max: 25
res_min: -15
res_max: 15
uom: "[m/s]"
comps:
  - c
  - e
bin_size: 0.2
c:
  fn: ""
  column: ""
  data: ""
  data_res: ""
  var_name: ""
e:
  fn: "thaao_e_10m_v_component_of_wind_"
  column: 2
  data: ""
  data_res: ""
  var_name: "v10"
t:
  fn: ""
  column: ""
  data: ""
  data_res: ""
t1:
  fn: ""
  column: ""
  data: ""
  data_res: ""
t2:
  fn: "AWS_THAAO_"
  column: ""
  data: ""
  data_res: ""
