name: winds
ref_x: t2
min: 0
max: 30
res_min: -10
res_max: 10
uom: "[m/s]"
comps:
  - c1
  - c2
  - e5
bin_size: 0.2
c1:
  fn: "thaao_c1_10m_wind_speed_"
  column: 2
  data: ""
  data_res: ""
  var_name: "si10"
c2:
  fn: "thaao_c2_10m_wind_speed_"
  column: 2
  data: ""
  data_res: ""
  var_name: "si10"
e5:
  fn: ""
  column: ""
  data: ""
  data_res: ""
  var_name: ""
t:
  fn: ""
  column: ""
  data: ""
  data_res: ""
t1:
  fn: ""
  column: ""
  data: ""
  data_res: ""
t2:
  fn: "AWS_THAAO_"
  column: "WS_aws"
  data: ""
  data_res: ""
