name: windd
ref_x: t2
min: 0
max: 360
res_min: -90
res_max: 90
uom: "[deg]"
comps:
  - c1
  - c2
  - e5
bin_size: 2
c1::
  fn: "thaao_c1_10m_wind_direction_"
  column: 2
  data: ""
  data_res: ""
  var_name: "wdir10"
c2:
  fn: "thaao_c2_10m_wind_direction_"
  column: 2
  data: ""
  data_res: ""
  var_name: "wdir10"
e5:
  fn: ""
  column: ""
  data: ""
  data_res: ""
  var_name: ""
t:
  fn: ""
  column: ""
  data: ""
  data_res: ""
t1:
  fn: ""
  column: ""
  data: ""
  data_res: ""
t2:
  fn: "AWS_THAAO_"
  column: "WD_aws"
  data: ""
  data_res: ""
