name: windv
ref_x: t2
min: -20
max: 20
res_min: -15
res_max: 15
uom: "[m/s]"
comps:
  - c1
  - c2
  - e5
bin_size: 0.2
c1:
  fn: ""
  column: ""
  data: ""
  data_res: ""
  var_name: ""
c2:
  fn: ""
  column: ""
  data: ""
  data_res: ""
  var_name: ""
e5:
  fn: "thaao_e5_10m_v_component_of_wind_"
  column: 2
  data: ""
  data_res: ""
  var_name: "v10"
t:
  fn: ""
  column: ""
  data: ""
  data_res: ""
t1:
  fn: ""
  column: ""
  data: ""
  data_res: ""
t2:
  fn: "AWS_THAAO_"
  column: ""
  data: ""
  data_res: ""
